import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { preview } from '../assets';
import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';

const CreatePost = () => {
  const navigate = useNavigate();

  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });

  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);
  const [queuePos, setQueuePos] = useState(null);

  // -------------------- SUBMIT POST --------------------
  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!form.prompt || !form.photo) {
      alert('Please generate an image first');
      return;
    }

    setLoading(true);

    try {
      const res = await fetch('https://ai-generation-server.onrender.com/api/v1/post', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      });

      if (!res.ok) throw new Error('Failed to create post');
      navigate('/');
    } catch (err) {
      alert(err.message);
    } finally {
      setLoading(false);
    }
  };

  // -------------------- INPUT --------------------
  const handleChange = (e) =>
    setForm({ ...form, [e.target.name]: e.target.value });

  const handleSurpriseMe = () => {
    setForm({ ...form, prompt: getRandomPrompt(form.prompt) });
  };

  // -------------------- POLL AI HORDE --------------------
  const pollAIHorde = async (jobId) => {
    const start = Date.now();
    const MAX_WAIT = 2 * 60 * 1000; // ⏱️ 3 minutes

    while (true) {
      if (Date.now() - start > MAX_WAIT) {
        throw new Error('⏰ Image generation timed out. Try again later.');
      }

      await new Promise((r) => setTimeout(r, 3000));

      const res = await fetch(
        `https://aihorde.net/api/v2/generate/status/${jobId}`
      );
      const data = await res.json();

      if (data.queue_position !== undefined) {
        setQueuePos(data.queue_position);
        console.log('⏳ Queue position:', data.queue_position);
      }

      if (data.done && data.generations?.length > 0) {
        return data.generations[0].img;
      }
    }
  };

  // -------------------- GENERATE IMAGE --------------------
  const generateImage = async () => {
    if (!form.prompt) {
      alert('Please enter a prompt');
      return;
    }

    try {
      setGeneratingImg(true);
      setQueuePos(null);

      // 1️⃣ Submit job to backend
      const submitRes = await fetch('https://ai-generation-server.onrender.com/api/v1/dalle', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: form.prompt }),
      });

      const { jobId } = await submitRes.json();
      if (!jobId) throw new Error('Failed to start image generation');

      console.log('🆔 Job ID:', jobId);

      // 2️⃣ Poll AI Horde directly
      const imageUrl = await pollAIHorde(jobId);

      // 3️⃣ Update UI
      setForm({ ...form, photo: imageUrl });
    } catch (err) {
      alert(err.message);
    } finally {
      setGeneratingImg(false);
      setQueuePos(null);
    }
  };

  // -------------------- UI --------------------
  return (
    <section className="max-w-7xl mx-auto px-4 flex justify-center">
      <div className="w-full max-w-3xl">
        <h1 className="font-extrabold text-[32px]">Create</h1>
        <p className="mt-2 text-gray-500">
          Create imaginative images generated by AI and share them.
        </p>

        <form className="mt-10" onSubmit={handleSubmit}>
          <div className="flex flex-col gap-5">
            <FormField
              LabelName="Your name"
              type="text"
              name="name"
              value={form.name}
              handleChange={handleChange}
            />

            <FormField
              LabelName="Prompt"
              type="text"
              name="prompt"
              value={form.prompt}
              handleChange={handleChange}
              isSurpriseMe
              handleSurpriseMe={handleSurpriseMe}
            />

            <div className="relative bg-gray-100 w-64 h-64 rounded-lg flex items-center justify-center">
              {form.photo ? (
                <img src={form.photo} alt="generated" className="w-full h-full object-contain" />
              ) : (
                <img src={preview} alt="preview" className="opacity-40 w-2/3" />
              )}

              {generatingImg && (
                <div className="absolute inset-0 bg-black/50 flex flex-col items-center justify-center">
                  <Loader />
                  {queuePos !== null && (
                    <p className="text-white text-sm mt-2">
                      {/* Queue position: {queuePos} */}
                    </p>
                  )}
                </div>
              )}
            </div>
          </div>

          <button
            type="button"
            onClick={generateImage}
            disabled={generatingImg}
            className="mt-5 bg-green-600 text-white px-5 py-2 rounded-md disabled:opacity-50"
          >
            {generatingImg ? 'Generating...' : 'Generate'}
          </button><br></br>

          <button
            type="submit"
            className="mt-8 bg-blue-600 text-white px-5 py-2 rounded-md"
          >
            {loading ? 'Sharing...' : 'Share with the community'}
          </button>
        </form>
      </div>
    </section>
  );
};

export default CreatePost;
